name: ubuntu_session
description: "Native Dart client library to access the GNOME Session Manager"
repository: https://github.com/canonical/ubuntu_session.dart
issue_tracker: https://github.com/canonical/ubuntu_session.dart/issues
version: 0.0.2

environment:
  sdk: ">=2.17.0 <3.0.0"

platforms:
  linux:

dependencies:
  dbus: ^0.7.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.16.0